# $schema: https://json.schemastore.org/dependabot-2.0.json

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/api"
    schedule:
      interval: "daily"
    reviewers:
      - "flagsmith/flagsmith-back-end"
    commit-message:
      prefix: "deps"
    labels:
      - "api"
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    reviewers:
      - "flagsmith/flagsmith-front-end"
    commit-message:
      prefix: "deps"
    labels:
      - "front-end"
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "daily"
    reviewers:
      - "flagsmith/flagsmith-docs"
    commit-message:
      prefix: "deps"
    labels:
      - "docs"
      - "dependencies"
