# https://github.com/actions/labeler

docs:
  - changed-files:
      - any-glob-to-any-file: docs/**

front-end:
  - changed-files:
      - any-glob-to-any-file: frontend/**

api:
  - changed-files:
      - any-glob-to-any-file: api/**

ci-cd:
  - changed-files:
      - any-glob-to-any-file: .github/**

infrastructure:
  - changed-files:
      - any-glob-to-any-file: infrastructure/**
