runtime: nodejs16

handlers:
- url: /static
  static_dir: build/static
  expiration: "365d"
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /images
  static_dir: build/images
  expiration: "4h"
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /fonts
  static_dir: build/fonts
  expiration: "365d"
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  SLACK_TOKEN: undefined
  EVENTS_SLACK_CHANNEL: undefined
  FLAGSMITH_ON_FLAGSMITH_API_KEY: 8KzETdDeMY7xkqkSkY3Gsg
  HEAP_API_KEY: undefined
  FLAGSMITH_ANALYTICS: undefined
  GOOGLE_ANALYTICS_API_KEY: undefined
  CRISP_WEBSITE_ID: undefined
  CAPTERRA_API_KEY: undefined
  LINKEDIN: undefined
  ALLOW_SIGNUPS: undefined
  PREVENT_SIGNUP: undefined
  ONLY_SUPERUSERS_CAN_CREATE_ORGANISATIONS: undefined
  MIXPANEL: undefined
  FLAGSMITH_API_URL: http://localhost:8000/api/v1/
  AMPLITUDE: undefined
  DELIGHTED_API_KEY: undefined
  ENABLE_MAINTENANCE_MODE: undefined
  ENABLE_INFLUXDB_FEATURES: False
  STATIC_ASSET_CDN_URL: /

env_variables:
  SLACK_TOKEN: undefined
  EVENTS_SLACK_CHANNEL: undefined
  FLAGSMITH_ON_FLAGSMITH_API_KEY: 8KzETdDeMY7xkqkSkY3Gsg
  HEAP_API_KEY: undefined
  FLAGSMITH_ANALYTICS: undefined
  GOOGLE_ANALYTICS_API_KEY: undefined
  CRISP_WEBSITE_ID: undefined
  CAPTERRA_API_KEY: undefined
  LINKEDIN: undefined
  ALLOW_SIGNUPS: undefined
  PREVENT_SIGNUP: undefined
  ONLY_SUPERUSERS_CAN_CREATE_ORGANISATIONS: undefined
  MIXPANEL: undefined
  FLAGSMITH_API_URL: http://localhost:8000/api/v1/
  AMPLITUDE: undefined
  DELIGHTED_API_KEY: undefined
  ENABLE_MAINTENANCE_MODE: undefined
  ENABLE_INFLUXDB_FEATURES: False
  STATIC_ASSET_CDN_URL: /

env_variables:
  SLACK_TOKEN: undefined
  EVENTS_SLACK_CHANNEL: undefined
  FLAGSMITH_ON_FLAGSMITH_API_KEY: 8KzETdDeMY7xkqkSkY3Gsg
  HEAP_API_KEY: undefined
  FLAGSMITH_ANALYTICS: undefined
  GOOGLE_ANALYTICS_API_KEY: undefined
  CRISP_WEBSITE_ID: undefined
  CAPTERRA_API_KEY: undefined
  LINKEDIN: undefined
  ALLOW_SIGNUPS: undefined
  PREVENT_SIGNUP: undefined
  ONLY_SUPERUSERS_CAN_CREATE_ORGANISATIONS: undefined
  MIXPANEL: undefined
  FLAGSMITH_API_URL: http://localhost:8000/api/v1/
  AMPLITUDE: undefined
  DELIGHTED_API_KEY: undefined
  ENABLE_MAINTENANCE_MODE: undefined
  ENABLE_INFLUXDB_FEATURES: False
  STATIC_ASSET_CDN_URL: /
