# You can use this to run the e2e tests in a docker container running in frontend below
# To run:
# docker-compose -f docker-compose-e2e-tests.pgpool.yml build
# docker-compose -f docker-compose-e2e-tests.pgpool.yml up

services:
  pg-0:
    extends:
      file: ../docker/common/db/pgpool.yml
      service: pg-0

  pg-1:
    extends:
      file: ../docker/common/db/pgpool.yml
      service: pg-1

  pgpool:
    extends:
      file: ../docker/common/db/pgpool.yml
      service: pgpool

  flagsmith-api:
    extends:
      file: ../docker/common/e2e/.e2e-tests.yml
      service: flagsmith-api
    environment:
      DATABASE_URL: postgresql://flagsmith:password@pgpool:5432/flagsmith
    depends_on:
      pgpool:
        condition: service_healthy
    links:
      - pgpool:pgpool

  frontend:
    extends:
      file: ../docker/common/e2e/.e2e-tests.yml
      service: frontend

volumes:
  pg_0_data:
    driver: local
  pg_1_data:
    driver: local
