# You can use this to run the e2e tests in a docker container running in frontend below
# To run:
# docker-compose -f docker-compose-e2e-tests.postgres.yml build
# docker-compose -f docker-compose-e2e-tests.postgres.yml up

version: '3'
services:
  db:
    image: ghcr.io/cloudnative-pg/postgresql:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flagsmith
    container_name: flagsmith_postgres

  flagsmith-api:
    extends:
      file: ./.common.docker-compose.e2e-tests.yml
      service: flagsmith-api

  frontend:
    extends:
      file: ./.common.docker-compose.e2e-tests.yml
      service: frontend
