# You can use this to run the e2e tests in a docker container running in frontend below
# To run:
# docker-compose -f docker-compose-e2e-tests.postgres.yml build
# docker-compose -f docker-compose-e2e-tests.postgres.yml up

services:
  postgres:
    extends:
      file: ../docker/common/db/.postgres.yml
      service: postgres
  volumes:
    - pgdata:/var/lib/postgresql/data

  flagsmith-api:
    extends:
      file: ../docker/common/e2e/.e2e-tests.yml
      service: flagsmith-api
    depends_on:
      - postgres
    links:
      - postgres:postgres

  frontend:
    extends:
      file: ../docker/common/e2e/.e2e-tests.yml
      service: frontend

volumes:
  pgdata:
