version: '3'

volumes:
  pg_11_data:

services:
  db:
    image: postgres:11.12-alpine
    pull_policy: always
    restart: unless-stopped
    volumes:
      - pg_11_data:/var/lib/postgresql/data:Z
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: flagsmith
      POSTGRES_PASSWORD: password
