name: Run E2E tests in docker unified environment
description: Run the E2E tests against docker unified environment

inputs:
  github_actor:
    description: Github actor
    required: true
  github_token:
    description: Github token
    required: true
  e2e_test_token_staging:
    description: The staging test token.
    required: true

runs:
  using: composite

  steps:
    - name: Set up Depot CLI
      uses: depot/setup-action@v1
      with:
        oidc: true

    - name: Expose GitHub Runtime
      uses: crazy-max/ghaction-github-runtime@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.github_actor }}
        password: ${{ inputs.github_token }}

    - name: Switch Docker Runtime to Depot
      run: depot configure-docker
      shell: bash
