name: Run E2E tests in docker unified environment
description: Run the E2E tests against docker unified environment

inputs:
  github_actor:
    description: Github actor
    required: true
  github_token:
    description: Github token
    required: true
  e2e_test_token_staging:
    description: The staging test token.
    required: true

runs:
  using: composite

  steps:
    - name: Set up Depot CLI
      uses: depot/setup-action@v1
      with:
        oidc: true

    - name: Expose GitHub Runtime
      uses: crazy-max/ghaction-github-runtime@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.github_actor }}
        password: ${{ inputs.github_token }}

    - name: Build docker-compose with unified-image
      working-directory: frontend
      env:
        E2E_TEST_TOKEN_STAGING: ${{ inputs.e2e_test_token_staging }}
        ENV: staging
        STATIC_ASSET_CDN_URL: /
      run: |
        depot bake -f docker-compose-e2e-tests.yml --load
      shell: bash
