name: Set up Depot for E2E Compose builds
description: Set up Depot for E2E Compose builds

inputs:
  github_actor:
    description: Github actor
    required: true
  github_token:
    description: Github token
    required: true

runs:
  using: composite

  steps:
    - name: Set up Depot CLI
      uses: depot/setup-action@v1
      with:
        oidc: true

    - name: Expose GitHub Runtime
      uses: crazy-max/ghaction-github-runtime@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.github_actor }}
        password: ${{ inputs.github_token }}

    - name: Switch Docker Runtime to Depot
      run: depot configure-docker
      shell: bash
