# reusable workflow
name: Run Docker E2E tests

on:
  workflow_call:
    inputs:
      registry-url:
        type: string
        description: Github Container Registry base URL
        required: false
        default: ghcr.io
      api-image:
        type: string
        description: Core API Docker image to use, e.g., `ghcr.io/flagsmith/flagsmith-api:main`
        required: true
      api-image-build-id:
        type: string
        description: Depot build ID for the Core API Docker image
        required: false
      e2e-image:
        type: string
        description: Frontend Docker with E2E capabilities image to use, e.g., `ghcr.io/flagsmith/flagsmith-e2e:main`
        required: true
      e2e-image-build-id:
        type: string
        description: Depot build ID for the Frontend Docker with E2E capabilities
        required: false
      tests:
        type: string
        description: Space-delimited list of E2E tests to be executed
        required: false
        default: ''
      concurrency:
        type: number
        description: The concurrent number of browsers to be used on testing
        required: false
        default: 3

jobs:
  run-e2e:
    name: "E2E${{ inputs.tests && format(': {0}', inputs.tests) || '' }}"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      id-token: write

    steps:
      - name: Cloning repo
        uses: actions/checkout@v4

      - name: Set up Depot CLI
        if: ${{ inputs.api-image-build-id || inputs.e2e-image-build-id }}
        uses: depot/setup-action@v1

      - name: Pull API image from Depot
        if: inputs.api-image-build-id
        run: depot pull ${{ inputs.api-image-build-id }} -t ${{ inputs.api-image }}

      - name: Pull E2E image from Depot
        if: inputs.e2e-image-build-id
        run: depot pull ${{ inputs.api-image-build-id }} -t ${{ inputs.e2e-image }}

      - name: Login to Github Container Registry
        if: ${{ !inputs.api-image-build-id && !inputs.e2e-image-build-id }}
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry-url }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests on dockerised frontend
        uses: nick-fields/retry@v3
        with:
          shell: bash
          command: |
            cd frontend
            make test
          max_attempts: 2
          retry_on: error
          timeout_minutes: 10
        env:
          opts: ${{ inputs.tests }}
          API_IMAGE: ${{ inputs.api-image }}
          E2E_IMAGE: ${{ inputs.e2e-image }}
          E2E_CONCURRENCY: ${{ inputs.concurrency }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          GITHUB_ACTION_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
