# reusable workflow
name: Build Docker Image

on:
  workflow_call:
    inputs:
      registry-url:
        type: string
        description: Github container registry base URL
        required: false
        default: ghcr.io
      file:
        type: string
        description: Path to the Dockerfile
        required: true
      image-name:
        type: string
        description: Image slug
        required: true
      build-args:
        type: string
        description: List of build-time variables
        required: false
      scan:
        type: boolean
        description: Whether to scan image for vulnerabilities
        required: false
        default: true
    outputs:
      image:
        description: Resulting image specifier
        value: ${{ inputs.registry-url }}/flagsmith/${{ inputs.image-name }}:${{ jobs.build.outputs.version }}

jobs:
  build:
    name: Build ${{ inputs.scan && 'and verify ' || '' }}${{ inputs.image-name }} image
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.meta.outputs.version }}

    permissions:
      packages: write
      id-token: write
      contents: read

    steps:
      - name: Cloning repo
        uses: actions/checkout@v4

      - name: Set up Depot CLI
        uses: depot/setup-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry-url }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ inputs.registry-url }}/flagsmith/${{ inputs.image-name }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr

      - name: Build and push image
        uses: depot/build-push-action@v1
        with:
          push: true
          build-args: ${{ inputs.build-args }}
          file: ${{ inputs.file }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Run Trivy vulnerability scanner
        if: ${{ inputs.scan }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.registry-url }}/flagsmith/${{ inputs.image-name }}:${{ steps.meta.outputs.version }}
