# reusable workflow
name: Run Docker E2E tests

on:
  workflow_call:
    inputs:
      registry-url:
        type: string
        description: Github Container Registry base URL
        required: false
        default: ghcr.io
      api-image:
        type: string
        description: Core API Docker image to use, e.g., `ghcr.io/flagsmith/flagsmith-api:main`
        required: true
      e2e-image:
        type: string
        description: Frontend Docker with E2E capabilities image to use, e.g., `ghcr.io/flagsmith/flagsmith-e2e:main`
        required: true
      tests:
        type: string
        description: Space-delimited list of E2E tests to be executed
        required: false
        default: ''
      concurrency:
        type: number
        description: The concurrent number of browsers to be used on testing
        required: false
        default: 3

jobs:
  run-e2e:
    name: "E2E${{ inputs.tests && format(': {0}', inputs.tests) || '' }}"
    runs-on: ubuntu-latest

    steps:
      - name: Cloning repo
        uses: actions/checkout@v4

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry-url }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests on dockerised frontend
        uses: nick-fields/retry@v3
        with:
          shell: bash
          command: |
            cd frontend
            make test
          max_attempts: 2
          retry_on: error
          timeout_minutes: 10
        env:
          opts: ${{ inputs.tests }}
          API_IMAGE: ${{ inputs.api-image }}
          E2E_IMAGE: ${{ inputs.e2e-image }}
          E2E_CONCURRENCY: ${{ inputs.concurrency }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          GITHUB_ACTION_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Output Core API container status and logs
        if: failure()
        working-directory: frontend
        run: |
          docker compose -f docker-compose-e2e-tests.yml logs flagsmith-api
        shell: bash
