# reusable workflow

on:
  workflow_call:


jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Cloning repo
        uses: actions/checkout@v4

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Deploy to Vercel
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          ENV: prod
        run: |
          npm ci --only=prod
          npm run env
          npm run bundle
          echo ${{ github.sha }} > CI_COMMIT_SHA
          npm install --global vercel@31.2.0
          echo "vercel --prod --token ${{ secrets.VERCEL_TOKEN }}"
