name: API Deploy to Production

on:
    push:
        tags:
            - '*'
        paths:
            - 'api/**'
            - '.github/**'

jobs:
    deploy-production:
        runs-on: ubuntu-latest
        name: API Deploy to Production
        container: flagsmith/eb-cli:latest
        environment: production
        timeout-minutes: 20

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Deploy API to Production
              uses: ./.github/actions/api-deploy-eb
              with:
                  beanstalk_environment_name: production-api
                  github_access_token: ${{ secrets.GH_PRIVATE_ACCESS_TOKEN }}
                  aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  flagsmith_saml_revision: v0.1.1
                  flagsmith_workflows_revision: v1.0.1

    run-tests:
        runs-on: ubuntu-latest
        name: Run E2E Tests
        environment: production
        needs: deploy-production

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Run E2E tests against production
              uses: ./.github/actions/e2e-tests
              with:
                e2e_test_token: ${{ secrets.E2E_TEST_TOKEN }}
                slack_token: ${{ secrets.SLACK_TOKEN }}
                environment: prod
