name: API Security Audit

on:
  schedule:
    - cron: 0 8 * * *

defaults:
  run:
    working-directory: api

jobs:
  audit:
    runs-on: ubuntu-latest
    name: API Security Audit

    steps:
      - name: Cloning repo
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run Audit
        run: |
          make install
          poetry self add poetry-audit-plugin==0.4.0
          poetry audit
