name: API Deploy to Production

on:
    push:
        tags:
            - '*'
        paths:
            - 'api/**'
            - '.github/**'

jobs:
    deploy-production:
        runs-on: ubuntu-latest
        name: API Deploy to Production
        container: flagsmith/eb-cli:latest
        environment: production
        timeout-minutes: 20

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Push to ElasticBeanstalk
              working-directory: api
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: eb deploy production-api -l "${GITHUB_SHA}" --timeout 20

    run-tests:
        runs-on: ubuntu-latest
        name: Run E2E Tests
        environment: production
        needs: deploy-production

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Test with Chromedriver
              working-directory: frontend
              env:
                  E2E_TEST_TOKEN_PROD: ${{ secrets.E2E_TEST_TOKEN }}
                  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
                  STATIC_ASSET_CDN_URL: /
              run: |
                  wget -q https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_96.0.4664.45-1_amd64.deb
                  sudo apt install --allow-downgrades -y ./google-chrome*.deb -f
                  google-chrome --version
                  node -v
                  npm i
                  export ENV=prod;
                  npm run env
                  npm run test
