name: API Deploy to Staging

on:
    push:
        branches:
            - main
        paths:
            - 'api/**'
            - '.github/**'

jobs:
    deploy-staging:
        runs-on: ubuntu-latest
        name: API Deploy to Staging
        container: flagsmith/eb-cli:latest
        environment: staging

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Push to ElasticBeanstalk
              working-directory: api
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: eb deploy staging-api -l "${GITHUB_SHA}"

    run-tests:
        runs-on: ubuntu-latest
        name: Run E2E Tests
        container: kylessg/bullet-train-nightwatch:1.1
        environment: staging

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Test with Chromedriver
              working-directory: frontend
              env:
                  E2E_TEST_TOKEN: ${{ secrets.E2E_TEST_TOKEN }}
              run: |
                  google-chrome --version
                  node -v
                  npm i
                  export ENV=staging;
                  npm run env
                  npm run test
