name: Frontend Deploy to Demo

on:
    push:
        branches:
            - main
        paths:
            - "frontend/**"
            - ".github/**"

defaults:
    run:
        working-directory: frontend

jobs:
    deploy-production:
        runs-on: ubuntu-latest
        name: Deploy to Vercel Demo
        environment: demo

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Setup Node.js 16.x
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: npm-${{ hashFiles('package-lock.json') }}
                  restore-keys: npm-

            - name: Deploy to Vercel
              env:
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  ENV: prod
              run: |
                  npm ci --only=prod
                  npm run env
                  npm run bundle
                  vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
