name: Frontend Deploy to Staging

on:
    push:
        branches:
            - main
            - chore/*
    pull_request:
        branches:
            - main

defaults:
    run:
        working-directory: frontend

jobs:
    deploy-develop:
        runs-on: ubuntu-latest
        name: Frontend Deploy to Staging
        environment: staging

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Build with Node.js 14.x
              uses: actions/setup-node@v1
              env:
                ENV: staging
              with:
                  node-version: 14.x
              run: |
                npm i
                npm run env
                npm run dotenv
                npm run bundledev

            - name: Run E2E Tests
              env:
                E2E_TEST_TOKEN: ${{ secrets.E2E_TEST_TOKEN }}
                ENV: staging
              run: |
                google-chrome --version
                node -v
                npm i
                npm run env
                npm run test

            - name: Setup Cloud SDK
              uses: google-github-actions/setup-gcloud@v0.2.0
              with:
                  project_id: bullet-train-front-end-staging
                  service_account_key: ${{ secrets.FRONTEND_GOOGLECLOUD_SERVICEACCOUNT_KEY }}

            - name: Deploy to App Engine
              run: gcloud app deploy --quiet
