name: Frontend Publish Docker Images

on:
    push:
        branches:
            - main
        tags:
            - "*"
        paths:
            - "frontend/**"
            - ".github/**"

jobs:
    build-frontend-dockerhub:
        runs-on: ubuntu-latest
        name: Frontend Publish Docker Image

        steps:
            - name: Cloning repo
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Docker metadata
              id: meta
              uses: docker/metadata-action@v3
              with:
                  images: |
                      flagsmith/flagsmith-frontend
                  flavor: |
                      latest=${{ startsWith(github.ref, 'refs/heads/main') }}
                  tags: |
                      type=ref,event=branch
                      type=semver,pattern={{version}}
                      type=semver,pattern={{major}}.{{minor}}

            - name: Write git info to Docker image
              run: |
                  cd api
                  echo ${GITHUB_SHA} > CI_COMMIT_SHA
                  echo ${{ steps.meta.outputs.tags }} > IMAGE_TAG

            - name: Download features
              run: >
                  curl --location --request GET 'https://api.flagsmith.com/api/v1/flags/'
                  --header 'X-Environment-Key: ${{ secrets.FLAGSMITH_ENVIRONMENT_KEY }}' > frontend/flags.json

            - name: Build and push amd64 images
              id: docker_build
              # only build amd images for latest tag
              if: ${{ !startsWith(github.ref, 'refs/tags/') }}
              uses: docker/build-push-action@v3
              with:
                  platforms: linux/amd64
                  file: frontend/Dockerfile
                  context: frontend/
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}

            - name: Build and push all architecture images on tags
              id: docker_build_arm
              # only build arm images on tags as they are slow to build
              if: ${{ startsWith(github.ref, 'refs/tags/') }}
              uses: docker/build-push-action@v3
              with:
                  platforms: linux/amd64,linux/arm64,linux/arm/v7
                  file: frontend/Dockerfile
                  context: frontend/
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}

            - name: Image digest
              run: echo ${{ steps.docker_build.outputs.digest }}
