name: Frontend Deploy to Production

on:
  push:
    branches:
      - main
      - ci/fix-frontend-deploy-workflow
    paths:
      - frontend/**
      - .github/**

defaults:
  run:
    working-directory: frontend

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run E2E Tests
    environment: production
    concurrency:
      group: e2e-tests-prod
      cancel-in-progress: true

    steps:
      - name: Cloning repo
        uses: actions/checkout@v4

      - name: Run E2E tests against production
        uses: ./.github/actions/e2e-tests
        with:
          e2e_test_token: ${{ secrets.E2E_TEST_TOKEN }}
          slack_token: ${{ secrets.SLACK_TOKEN }}
          environment: prod

  deploy-production:
    runs-on: ubuntu-latest
    name: Deploy to Vercel Production
    environment: production
    needs: run-tests

    steps:
      - name: Deploy to production
        uses: ./.github/workflows/.reusable-frontend-deploy.yml


  deploy-demo:
    runs-on: ubuntu-latest
    name: Deploy to Vercel Demo
    environment: demo
    needs: run-tests

    steps:
      - name: Deploy to demo
        uses: ./.github/workflows/.reusable-frontend-deploy.yml
