name: Frontend Deploy to Staging

on:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

defaults:
    run:
        working-directory: frontend

jobs:
    deploy-staging:
        runs-on: ubuntu-latest
        name: Deploy to Staging
        environment: staging

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Setup Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - uses: amondnet/vercel-action@v20
              with:
                vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
                #github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
                vercel-args: "--prod" #Optional
                vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} #Required
                vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required
                working-directory: .
