name: 'Manual E2E tests'

on:
  workflow_dispatch:
    inputs:
      e2e-token:
        description: 'The authentication token used by the E2E process'
        required: true
      e2e-concurrency:
        description: 'The concurrency value to use when running the E2E process'
        default: 3
        type: number
      api-url:
        description: 'Which database service to use to run the API against'
        default: 'https://api.flagsmith.com/api/v1/'
  push:

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        working-directory: frontend
        env:
          E2E_TEST_AUTH_TOKEN: ${{ inputs.e2e-token || 'b682133ed570d1ebf0a11fbdefda2747' }}
          FLAGSMITH_API_URL: ${{ inputs.api-url || 'http://3.8.139.31:8000/api/v1/' }}
          E2E_CONCURRENCY: ${{ inputs.e2e-concurrency || 1 }}
        run: npm run test
