name: Platform Pull Requests

on:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

jobs:
    run-e2e-tests:
        if: github.event.pull_request.draft == false
        runs-on: ubuntu-latest
        name: Full E2E tests

        steps:
            - name: Cloning repo
              uses: actions/checkout@v3

            - name: Run E2E tests against local
              uses: ./.github/actions/e2e-tests
              with:
                E2E_TEST_TOKEN_STAGING: ${{ secrets.E2E_TEST_TOKEN }}
                ENV: staging
                slack_token: ${{ secrets.SLACK_TOKEN }}
                environment: staging
                enable_influxdb_features: false

