name: Platform Pull Requests

on:
    - pull_request

jobs:
    run-e2e-tests:
        runs-on: ubuntu-latest
        name: Full E2E tests
        container: flagsmith/nightwatch:1.2

        services:
            postgres:
                image: postgres:13
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: flagsmith
                ports: ['5432:5432']
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
            api:
                image: flagsmith-api:latest
                env:
                    E2E_TEST_AUTH_TOKEN: some-token
                    DJANGO_ALLOWED_HOSTS: '*'
                    DATABASE_URL: postgresql://postgres:postgres@postgres:5432/flagsmith
                ports: ['8000:8000']

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Test with Chromedriver
              working-directory: frontend
              env:
                  E2E_TEST_TOKEN_LOCAL: some-token
                  ENV: local
              run: |
                  google-chrome --version
                  node -v
                  npm i
                  npm run env
                  npm run test
