name: Platform Pull Requests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - docs/**
      - infrastructure/**

jobs:

  run-tests:
    runs-on: ubuntu-latest
    name: Run E2E Tests
    environment: prod
    concurrency:
      group: e2e-tests-prod
      cancel-in-progress: true

    steps:
      - name: Cloning repo
        uses: actions/checkout@v4

      - name: Run E2E tests against production
        uses: ./.github/actions/e2e-tests
        with:
          e2e_test_token: ${{ secrets.E2E_TEST_TOKEN }}
          environment: prod
