name: Platform Test Merge to Main

on:
  push:
    branches:
      - main

jobs:
  docker-build-api:
    name: Build API Image
    uses: ./.github/workflows/.reusable-docker-build.yml
    with:
      file: api/Dockerfile
      image-name: flagsmith-api

  run-e2e-tests-local:
    needs: docker-build-api
    uses: ./.github/workflows/.reusable-local-e2e-tests.yml
    with:
      api-image: ${{ needs.docker-build-api.outputs.image }}
