name: Platform Test Merge to Main

on:
    push:
        branches:
            - main

jobs:
    run-e2e-tests:
        runs-on: ubuntu-latest
        name: Full E2E tests

        services:
            postgres:
                image: postgres:11.12-alpine
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: flagsmith
                ports: ['5432:5432']
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Run Local API
              uses: ./.github/actions/run-local-api
              with:
                  e2e_test_token: some-token
                  database_url: postgres://postgres:postgres@localhost:5432/flagsmith
                  sentry_sdk_dsn: ${{ secrets.SENTRY_SDK_DSN }}
                  sendgrid_api_key: ${{ secrets.SENDGRID_API_KEY }}

            - name: Run E2E tests against local
              uses: ./.github/actions/e2e-tests
              with:
                e2e_test_token: some-token
                slack_token: ${{ secrets.SLACK_TOKEN }}
                environment: local
                enable_influxdb_features: false
