name: Platform Test Merge to Main

on:
  push:
    branches:
      - main

jobs:
  docker-build-api:
    name: Build API Image
    uses: ./.github/workflows/.reusable-docker-build.yml
    with:
      file: api/Dockerfile
      image-name: flagsmith-api

  docker-build-e2e:
    name: Build E2E Image
    uses: ./.github/workflows/.reusable-docker-build.yml
    with:
      file: frontend/Dockerfile.e2e
      image-name: flagsmith-e2e
      scan: false

  run-e2e-tests-local:
    needs: [docker-build-api, docker-build-e2e]
    uses: ./.github/workflows/.reusable-docker-e2e-tests.yml
    with:
      api-image: ${{ needs.docker-build-api.outputs.image }}
      e2e-image: ${{ needs.docker-build-e2e.outputs.image }}
