name: API Deploy

on:
  workflow_call:
    inputs:
      beanstalk_environment_name:
        required: true
        type: string
      flagsmith_saml_revision:
        required: false
        type: string
        default: main
      github_environment_name:
        required: true
        type: string
    secrets:
      github_access_token:
        required: true
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true

jobs:
    deploy:
        environment: ${{ inputs.github_environment_name }}
        runs-on: ubuntu-latest
        name: API Deploy
        container: flagsmith/eb-cli:latest
        timeout-minutes: 20

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Add SAML package
              working-directory: api
              env:
                FLAGSMITH_SAML_REVISION: ${{ inputs.flagsmith_saml_revision }}
              run: |
                echo "Downloading and injecting flagsmith-saml module..."
                TARBALL_URL="https://github.com/flagsmith/flagsmith-saml/tarball/${FLAGSMITH_SAML_REVISION}" 
                mkdir /tmp/flagsmith-saml
                curl -L -u token:${{ secrets.github_access_token }} $TARBALL_URL | tar --strip-components=1 -xz -C /tmp/flagsmith-saml -- 
                mv /tmp/flagsmith-saml/saml .

            - name: Add SAML dependencies
              working-directory: api
              run: |
                echo "Adding SAML requirements to requirements.txt..."
                cat /tmp/flagsmith-saml/requirements.txt >> requirements.txt

            - name: Push to ElasticBeanstalk
              working-directory: api
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
              run: eb deploy ${{ inputs.beanstalk_environment_name }} -l \"${GITHUB_SHA}\" --timeout 20
